In [2]:
import numpy as np

In [3]:
# The column names for this np array ['Apple', 'Beef', 'Eggs', 'Potatoes']
# The row names for this np array ['Carbonhydrates', 'Protien', 'Fat']
a = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]
             ])

In [4]:
# TODO: Calculate the sum. Which axis should you use? axis=0? axis=1?  

In [7]:
# Print out the total Calories of ['Apple', 'Beef', 'Eggs', 'Potatoes']
print(np.sum(a, axis=0).reshape(1, -1))

[[ 59.  239.  155.4  76.9]]


In [8]:
# Print out the total Calories of ['Carbonhydrates', 'Protien', 'Fat']
print(np.sum(a, axis=1).reshape(-1, 1))

[[128.4]
 [165.2]
 [236.7]]


In [13]:
# TODO: Calculate the ingredient percentage of each food!
total_cal_item = np.sum(a, axis=0).reshape(1, -1)
total_cal_chem = np.sum(a, axis=1).reshape(-1, 1)
perce_each_food = a/total_cal_item*100
print(perce_each_food)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
