In [22]:
import numpy as np
import time

In [23]:
# TODO: Use numpy to create 5 arrays:
# 1 1D vector
# 1 2D array with shape (2, 3)
# 1 2D ones array with shape (2, 3)
# 1 2D zeros array with shape(2, 3)
# 2 2D array with random values

In [24]:
# 1D vector
# Remember to print its shape
vec = np.array([1, 2, 3])
print(vec)
print(vec.shape)

[1 2 3]
(3,)


In [25]:
# 2D array
# Rememebr to print its shape
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [26]:
# 2D ones array
# Remember to print its shape
ones = np.ones((2, 3))
print(ones)
print(ones.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [27]:
# 2D zeros array
# Remember to print its shape
zeros = np.zeros((2, 3))
print(zeros)
print(zeros.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [28]:
# Element-wise Addition
add = arr + ones
print(add)
print(add.shape)

[[2. 3. 4.]
 [5. 6. 7.]]
(2, 3)


In [29]:
# Element-wise Multiplication
mul = arr * add
print(mul)
print(mul.shape)

[[ 2.  6. 12.]
 [20. 30. 42.]]
(2, 3)


In [30]:
# Dot Product
# arr(2, 3) add(2,3), so one of the matirx needs to be transposed
dot1 = arr.dot(add.T)
dot1 = np.dot(arr, add.T)
print(dot1)
print(dot1.shape)

[[20. 38.]
 [47. 92.]]
(2, 2)


In [31]:
# Create 2D array with random values of shape (1000000, 1)
rand1 = np.random.rand(1000000, 1)
rand2 = np.random.rand(1000000, 1)
print(rand1)


[[0.91681881]
 [0.83075166]
 [0.43667868]
 ...
 [0.44411162]
 [0.62558901]
 [0.5930908 ]]


In [32]:
# TODO: Use vectorization to calculate the dot product
# call time.time() twice to calculate the total run time 

In [33]:
begin = time.time()
ans1 = rand1.T.dot(rand2)
finish = time.time()

In [34]:
print('Time:', finish-begin)
print(ans1)

Time: 0.0009980201721191406
[[250042.46044397]]


In [35]:
# TODO: Use for loop to calculate the dot product
# call time.time() twice to calculate the total run time 

In [36]:
start = time.time()
ans2 = 0
for i in range(rand2.shape[0]):
    ans2 += rand1[i][0] * rand2[i][0]
end = time.time()

In [37]:
print('Time:', end-start)
print(ans2)

Time: 0.4989964962005615
250042.46044397
